{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccounts.proxy.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "proxy.serviceAccountName" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
# Empty until PodSecurityPolicies added as no explicit permissions are
# required
rules:
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: proxy
  apiGroup: rbac.authorization.k8s.io
{{- end }}
